apiVersion: v1
kind: Namespace
metadata:
  name: test-ml-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-ml-score-api
  name: test-ml-score-api
  namespace: test-ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ml-score-api
  template:
    metadata:
      labels:
        app: test-ml-score-api
    spec:
      containers:
      - image: alexioannides/test-ml-score-api:latest
        name: test-ml-score-api
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: test-ml-score-lb
  labels:
    app: test-ml-score-api
  namespace: test-ml-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: test-ml-score-api
